name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo6 cmake libffi-dev libssl-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk

          # download cmdline-tools stable
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools cmdline-tools/latest

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Accept Android licenses (IMPORTANT FIX)
        run: |
          yes | sdkmanager --licenses || true

      - name: Install stable SDK packages (NO build-tools 37)
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "build-tools;34.0.0"

      - name: Force Buildozer config
        run: |
          buildozer init || true

          sed -i 's/android.api = .*/android.api = 33/' buildozer.spec || true
          sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec || true
          sed -i 's/android.build_tools_version = .*/android.build_tools_version = 34.0.0/' buildozer.spec || true

      - name: Build APK
        run: |
          buildozer -v android debug